### ISSUE TITLE
bad user behind a firewall...

### ISSUE THREAD

**Issue by linleyj** [ropensci/clifro#13]
Hi there, 

I'm having an issue using clifro for user data behind a firewall. It works off-site though.
It might be similar to this issue:
https://github.com/ropensci/clifro/issues/7

Here is what I've been trying:
options(RCurlOptions = list(proxy = 'http://proxy.pfr.co.nz:8080'))

### Works on and offsite
public.cfuser = cf_user()
daily.wind.rain.dt = cf_datatype(c(2, 3), c(1, 1), list(4, 1), c(1, NA))
reefton.st = cf_station()
daily.datalist = cf_query(user = public.cfuser,
                          datatype = daily.wind.rain.dt,
                          station = reefton.st,
                          start_date = "2012-01-01 00",
                          end_date = "2013-01-01 00")

### Bad user error from PFR; works offsite
daily.datalist = cf_query(user = cf_user(username = "****",  password = "****"),
datatype = daily.wind.rain.dt,
station = reefton.st,
start_date = "2012-01-01 00",
end_date = "2013-01-01 00")

traceback()
 Error in validObject(.Object) : invalid class “cfUser” object: Bad Login 
9.
stop(msg, ": ", errors, domain = NA) 
8.
validObject(.Object) 
7.
.local(.Object, ...) 
6.
initialize(value, ...) 
5.
initialize(value, ...) 
4.
new("cfUser", username = username, password = password)

**Comment by blasee** [comment]
Hi Linley, could you please try passing the RCurl options to the `cf_curl_opts` function instead?

**Comment by linleyj** [comment]
Yes, had started with that. Same issue:
> ### Bad user error from PFR; works from home
> cf_curl_opts(.opts = list(proxy = "http://proxy.pfr.co.nz:8080",  ssl.verifypeer = FALSE))
#password removed after the fact
> daily.datalist = cf_query(user = cf_user(username = "***",  password = "****"),
+ datatype = daily.wind.rain.dt,
+ station = reefton.st,
+ start_date = "2012-01-01 00",
+ end_date = "2013-01-01 00")
 Show Traceback
 
 Rerun with Debug
 Error in validObject(.Object) : invalid class “cfUser” object: Bad Login In addition: Warning message:
XML content does not seem to be XML: '3c
21
44
4f
43
54
59
50
45
20
48
54
4d
4c
20
50
55
42
4c
49
43
20
22
2d
2f
2f
57
33
43
2f
2f
44
54
44
20
48
54
4d
4c
20
34
2e
30
31
20
54
72
61
6e
73
69
74
69
6f
6e
61
6c
2f
2f
45
4e
22
0a
20
20
20
20
20
20
22
68
74
74
70
3a
2f
2f
77
77
77
2e
77
33
2e
6f
72
67
2f
54
52
2f
68
74
6d
6c
34
2f
6c
6f
6f
73
65
2e
64
74
64
22
3e
0a
3c
68
74
6d
6c
3e
0a
3c
68
65
61
64
3e
0a
3c
74
69
74
6c
65
3e
44
69
73
70
6c
61
79
20
55
73
65
72
20
49
6e
66
6f
3c
2f
74
69
74
6c
65
3e
0a
3c
6d
65
74
61
20
68
74
74
70
2d
65
71
75
69
76
3d
22
43
6f
6e
74
65
6e
74
2d
54
79
70
65
22
20
63
6f
6e
74
65
6e
74
3d
22
74
65
78
74
2f
68
74
6d
6c
3b
20
63
68
61
72
73
65
74
3d
69
73
6f
2d
38
38
35
39
2d
31
22
3e
0a
3c
6c
69
6e
6b
20
72
65
6c
3d
73
74
79
6c
65
73
68
65
65
74
20
74
79
70
65
3d
22
74
65
78
74
2f
63
73
73
22
20
68
72
65
66
3d
22
68
74
74
70
73
3a
2f
2f
63
6c
69
66
6c
6f
2e
6e
69
77
61
2e
63
6f
2e
6e
7a
2f
66
6f
72
6d
61
74
2e
63
73
73
22
3e
0a
3c
21
2d
2d
6a
73
5f
73
6d
61 [... truncated]

**Comment by blasee** [comment]
OK thanks for issuing this. I'll be able to have a look next week.

**Comment by blasee** [comment]
Hi @linleyj,

I think the error may be due to an invalid call to `cf_user`. Could you please update your code from:

```
daily.datalist = cf_query(user = cf_user(username = "", password = ""), 
                          ...)
```
to:
```
daily.datalist = cf_query(user = cf_user(),
                          ...)
```

This will use the default arguments of `cf_user(username = "public", password = character()`), instead of passing an empty string to the `username` argument.

**Comment by mwohlers** [comment]
Hi @linleyj  the problem and solution was similar to that described here [https://github.com/ropensci/clifro/issues/7](url). Thanks @HaizhenWu !

Again it was a problem with the postForm function, this time called within the cf_login function as part of cfUser.R. Using the proxy seems to make postForm return raw rather than a character string and so must be converted. 

This only seemed to be an issue when specifying a non default username/password so I changed lines 191 through 201 in [https://github.com/ropensci/clifro/blob/master/R/cfUser.R](url) to convert the postForm output to character if needed before passing to htmlParse and continuing as normal.

```  
else{
    myform<-postForm(
      "https://cliflo.niwa.co.nz/pls/niwp/wa.logindb",
      cusername = object@username,
      cpwd = rot(object@password, 3),
      ispopup = "false",
      submit = "login",
      curl = curl,
      .opts = list(cainfo = cert))
	  if(is.raw(myform)) {myform <- rawToChar(myform)}
	  login_html = htmlParse(myform)
    result = xmlValue(querySelector(login_html, "h1"))
  }
```  
It then seemed to work for me. 

As mentioned by @blasee the default cf_user work. I'm assuming this is because it doesn't call postForm.

**Comment by blasee** [comment]
Thanks @mwohlers! Great stuff.

**Comment by linleyj** [comment]
@mwohlers @blasee 
yes! This worked brilliantly! Thanks so much 👍 :-D
