### ISSUE TITLE
ORCID identifier and search keywords for codemetar

### ISSUE THREAD

**Issue by chrisfan24** [ropensci/clifro#16]
👋  @blasee 

I'm using codemetar to create JSON-LD metadata for rOpenSci packages. I need some info and it'd be awesome if you could help me out with this - in particular, I need your ORCID identifier as well as some keywords for the package that would help for search.

Thanks and let me know if you need me to elaborate on what I'm doing!

**Comment by blasee** [comment]
Hi @chrisfan24,

Great stuff!

ORCID ID:  orcid.org/0000-0001-6841-4312
keywords: r, ropensci, zealand, weather, climate, cliflo, data, api, windrose, rain, wind, temperature
