### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/clifro#2]
hey @blasee   - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

* you already keep a `NEWS` file, thanks!
* thanks for git tagging!
* You have used the [releases tab](https://github.com/ropensci/clifro/releases) on this repo to include the associated NEWS items for each tag/version - thanks for that, but can you make sure to git tag each release, and put the NEWS items in each release in the releases tab? e.g., right now CRAN is at version 2.4-1, while most recent release is at 2.4-0 -  thanks! 😄

**Comment by sckott** [comment]
Hi again @blasee - The news doesn’t seem to have changes for the recent CRAN release `v3.1-2` https://github.com/ropensci/clifro/blob/master/NEWS.md - Neither do the releases https://github.com/ropensci/clifro/releases

Could you make sure to include news for each CRAN release and put those bits in tagged release notes, thanks!

**Comment by sckott** [comment]
hi @blasee , thanks for the release notes in https://github.com/ropensci/clifro/releases/tag/v3.2-1 - Would it be possible to give more detail than 

> Fixed issue #21

I like that you link to the issue, but at least a brief summary of what was changed would be useful

**Comment by blasee** [comment]
Sure thing! Keep up the great work @sckott!
