### ISSUE TITLE
missingArg correction in windrose function

### ISSUE THREAD

**Issue by swmpkim** [ropensci/clifro#21]
Line 103 of cfData-plotMethods.R (the beginning of `windrose` ) should say:

`if (missingArg(speed))`

rather than:
```
  if (missingArg(direction))
    stop("speed can't be missing")

  if (missingArg(direction))
    stop("direction can't be missing")
```

**Comment by swmpkim** [comment]
I doubt this is worth a separate issue, but if you're modifying windrose for the above issue, there's also a minor typo on line 124; to be consistent with line 126 just add an 's' to speed:
`stop("wind speed needs to be numeric")`

I'm looking at this function so closely because I'm trying to improve functions that I write, and I've always liked making windroses from clifro. It's a really useful and well-written function; thanks!

**Comment by blasee** [comment]
Thanks @swmpkim!
