### ISSUE TITLE
cf_find_station error when returning distances from a latlon search

### ISSUE THREAD

**Issue by blasee** [ropensci/clifro#22]
For searches using 'latlon', the function returns a vector of distances that does not match the length of the other vectors in the data frame. For example, I want to search for stations within a 10km radius of the main Takaka township that contain daily rain data.

```r
library(clifro)

# Create a daily rain object
rain = cf_datatype(3, 1, 1)

# Search for the open stations containing daily rain
cf_find_station(lat = -40.85, long = 172.8, rad = 10, search = "latlong", datatype = rain)
```
`Error in data.frame(name = agent_name[seq(2, length(agent_name), by = 2)],  : 
  arguments imply differing number of rows: 2, 5`

**Comment by blasee** [comment]
This now becomes an issue when a datatype is not selected:

```r
library(clifro)

# Search for the open stations using coordinates, without a datatype
cf_find_station(lat = -40.85, long = 172.8, rad = 10, search = "latlong")
```

`Error in data.frame(name = agent_name[seq(2, length(agent_name), by = 2)],  : 
  arguments imply differing number of rows: 4, 0`

**Comment by markbneal** [comment]
The example from help file (cf_find_station {clifro} ) does not work, with similar error.
```
beehive.st = cf_find_station(lat = -41.2784, long = 174.7767, rad = 10, search = "latlong")
```
