### ISSUE TITLE
Amount of data accessible with clifro?

### ISSUE THREAD

**Issue by sckott** [ropensci/clifro#23]
👋 as part of preparing an ropensci annual report, we're trying to estimate amount of data the various pkgs in our suite provide access to.

Do you have a sense for how much data (e.g., in GB) one can access through this pkg? How many stations?  Other metrics?

thanks!

**Comment by blasee** [comment]
Hi @sckott, sorry, I forgot I hadn't replied to this. 

I've emailed NIWA to ask if they had any insights on the volume of data (e.g. in GB), and I'm awaiting a reply. I can provide some other metrics soon though.

Cheers!
Blake

**Comment by sckott** [comment]
thanks!

**Comment by blasee** [comment]
Hi @sckott,

Here's what it says on the CliFlo webpage

> CliFlo is the web system that provides access to New Zealand's National Climate Database.
>
> The climate database holds data from about 6500 climate stations which have been operating for various periods since the earliest observations were made in the year 1850. The database continues to receive data from over 600 stations that are currently operating.
>
> CliFlo returns raw data and statistical summaries. Raw data include ten minute, hourly and daily frequencies. Statistical data include about eighty different types of monthly and annual statistics and six types of thirty−year normals.

Data queried through *clifro* suggests that there are actually 8,360 unique stations available (although some of these may be successors at the same location), and 3,388 of these are classified as 'open' stations in *clifro*, which means that they have had data updated within the past 4 weeks.

It's hard for me to get an idea on the volume of data without a little more help, but I'll let you know if or when I get anywhere.

See below for a map showing the geographical extent of the stations. 

![cliflo_stations](https://user-images.githubusercontent.com/5362994/66791309-69e36880-ef3f-11e9-8cef-07a7261991d4.PNG)

**Comment by sckott** [comment]
Great, thanks very much for this. I think that will suffice, no need to go after size of data if it's more work.
