### ISSUE TITLE
cf_user returns error recently in August 2016

### ISSUE THREAD

**Issue by ldatamine** [ropensci/clifro#3]
Hello,

Recently in August 2016, running 

`me=cf_user("username", "password")`

would return:

> Error in function (type, msg, asError = TRUE)  : 
>   SSL certificate problem: unable to get local issuer certificate

Looks like there might have been an update of the certificate on NIWA's side. Is this something that can be fixed in the package, or is it not relevant?

Thanks!

**Comment by ldatamine** [comment]
Hello,

Just an update:

NIWA confirmed that it has recently changed it’s proxy server. CliFlo is still only http not https (which uses an SSL certificate) - so a user can ignore the certificate.

However, cf_user("username", "password") does not seem to have an easy way to ignore the certificate.

Thanks!

**Comment by blasee** [comment]
Hi there,

Thanks for opening this issue! I've just committed a fix that works on my local Ubuntu 14.04.5 LTS (f836831). I will test it some more when I have access to a Windows machine tomorrow. I will submit clifro 3.0-0 to CRAN in the next day or so - assuming all goes well.

Thanks again!

**Comment by ldatamine** [comment]
Thank you very much! Really appreciate it!

**Comment by blasee** [comment]
`clifro` v3.0-0 is now up on CRAN that addresses this issue and works on the multiple platforms I've tested.

Thanks again for the bug report.
Blake
