### ISSUE TITLE
Can't filter datatypes in cf_find_station

### ISSUE THREAD

**Issue by gis-maker** [ropensci/clifro#31]
Hi, 
here is an example from vignette I try to run

library(clifro)
library(tidyverse)

public.user = cf_user()
public.user

daily.dt = cf_datatype(c(2, 3), c(1, 1), list(4, 1), c(1, NA))
daily.dt

cf_find_station("reefton EWS", datatype = daily.dt)

> cf_find_station("reefton EWS", datatype = daily.dt)
Error in tail(html_table(doc, header = TRUE, fill = TRUE), 1)[[1]] : 
  subscript out of bounds

Thanks

**Comment by blasee** [comment]
Hi @gis-maker,

Thanks for submitting this bug report. 

I've updated the development version of *clifro*, which seems to have fixed this issue, however now I'm getting a 404 HTML error. I've emailed the CliFlo team at NIWA about this and I'll update you when I hear back.

**Comment by blasee** [comment]
Hi @gis-maker,

The latest development version seems to have fixed this bug, and NIWA have fixed the 404 HTML error I was getting.

```r
if (!require(remotes))
    install.packages("remotes")
    library(remotes)

remotes::install_github("ropensci/clifro")
library(clifro)

daily.dt = cf_datatype(c(2, 3), c(1, 1), list(4, 1), c(1, NA))
cf_find_station("reefton EWS", datatype = daily.dt)
```

**Comment by gis-maker** [comment]
Hi @blasee ,

Thank! This works great now.
