### ISSUE TITLE
cf_find_station() error with datatype

### ISSUE THREAD

**Issue by moreron** [ropensci/clifro#33]
I'm experiencing an error on cf_find_station() whenever I include the datatype.  I'm on clifro version 3.2-5 with R4.2.0.

The vignette example 
```
# Create a clifro datatype for hourly rain
hourly.rain.dt = cf_datatype(3, 1, 2)

# Conduct the search
cf_find_station("takaka", datatype = hourly.rain.dt)
```
Returns this error

Error:
! Assigned data `dmy(doc_table$Start, tz = "NZ")` must be compatible with existing data.
✖ Existing data has 1 row.
✖ Assigned data has 0 rows.
ℹ Row updates require a list value. Do you need `list()` or `as.list()`?
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Unknown or uninitialised column: `Start`. 
> cf_find_station(datatype = daily.rain.dt)
Error in tail(html_table(doc, header = TRUE, fill = TRUE), 1)[[1]] : 
  subscript out of bounds

I've tried a couple of different cf_datatypes and all return the error, though the other search functions like region and latlong work fine.

Awesome package BTW

**Comment by blasee** [comment]
Hey @moreron,

Thanks for submitting a bug report!

I believe this issue has been fixed in the development version of *clifro*. Please try your code with the latest version, a snippet is provided below so you can copy-paste.

```R
if(!require(remotes))
    install.packages("remotes")
remotes::install_github("ropensci/clifro")

# Create a clifro datatype for hourly rain
hourly.rain.dt = cf_datatype(3, 1, 2)

# Conduct the search
cf_find_station("takaka", datatype = hourly.rain.dt)
```

Returns:

```R
         name network agent      start        end open distance       lat      lon
1) Takaka Ews  F02885 23849 2002-06-02 2022-07-23 TRUE       NA -40.86364 172.8057
```

Let me know how you go, and if you run into more issues :-)

Thanks!

**Comment by moreron** [comment]
Tried a couple of cf_datatype queries, works as advertised :) 

Thanks for the quick fix Blake!

**Comment by blasee** [comment]
Great, thanks for helping improve `clifro`!

I'll submit the latest version to CRAN in the coming days.
