### ISSUE TITLE
Access to annual observations

### ISSUE THREAD

**Issue by johnForne** [ropensci/clifro#34]
Kia ora 
I'd like to access annual average temperature data for all open sites in cliflo.
I'm new to using cliflo and clifro so I'm unsure what is the most efficient way of doing this.
I think I've got a couple of questions/issues that I'd really appreciate your help with

1. how to use cf_find_station() to access all (open) stations? So far I can only see how to access a single region at a time, e.g. 
`kaitaia_stn <- cf_find_station("Kaitaia", search = "region", status = "open)`.

I was then going to loop over the list of names to download them all then bind them together.

Question is: Is there any way to down load all open stations without having to query region by region?

2. When creating clifro Datatypes, I am unclear how to access Statistics Calculated from Observations > Annual Normals > Total rainfall (mm)? Curently, there only seems to be the option of selecting datatypes within Daily and Hourly Observations. From https://cliflo.niwa.co.nz/pls/niwp/wa.list_codes I think I'm after Code 900. But it is unclear how to request this...

Thanks in advance,

John

**Comment by johnForne** [comment]
Kia ora Blake
Thanks heaps for your thorough and very helpful reply - much appreciated :)
Apologies for the slow acknowledgement/thanks.

Your code is what I'm after. I can now `cf_query()` all cliflo sites and can convert the daily observations into annual averages, which is great.

However, I'm running out of the 2,000,000 rows of data I can access from cliflo using my subscription (do you know what there is a 2M cap?). Anyhow, when I run the following code to download daily rainfall data for all open sites with at least 30 years of data I get the following error message.

> connecting to CliFlo...
reading data...
Error: No rows? See this help link <http://cliflo.niwa.co.nz/pls/niwp/wh.do_help?id=nodata> for possible reasons

I'm ok to simply skip a site if it has no rows of data.

Do you know how I could tweak the following code so that it runs through all sites in `stn_list` regardless of whether some of them have no rows of data?

```
# load libraries
library(tidyverse)
library(lubridate)
library(clifro)

rain_stations = cf_find_station(
  lat = -40.7,
  long = 172.465,
  rad = 840,
  search = "latlong",
  status = "open"
)

# select (open) sites with at least 30 years between start and end dates----
rain_stations_ <- rain_stations %>%
  as_tibble() %>% 
  mutate(
    interval_ = interval(start, end),
    years = interval_/years(1)) %>%
  filter(years >= 30)

# visualise the subset of stations----
rain_stations_cfStation <- rain_stations_ %>%
  pull(agent) %>% 
  cf_station()

rain_stations_cfStation %>% cf_save_kml(file_name = "testing_OAC2023/rainfall/nz_stations_open_30")


stn_list <- rain_stations_ %>%
pull(agent)

output <- list()
for (i in stn_list){
  rain_stations_cf <- cf_station(i) 
  
  output[[i]] <- cf_query(user = me,
                          datatype = rain_dt,
                          station = rain_stations_cf,
                          # start_date = "1991-01-01 00",
                          start_date = "2017-01-01 00",
                          end_date = "2022-01-01 00") %>%
    as_data_frame()
}

df <- output %>% bind_rows()
```

**Comment by blasee** [comment]
Hi @johnForne,

The following works for me, I've just made a few minor tweaks to your code:

```r
rain_stations = cf_find_station(
  lat = -40.7,
  long = 172.465,
  rad = 840,
  datatype = rain_dt, # Add the rain datatype to the query
  search = "latlong",
  status = "open"
)

# ...

# Set up an empty list
output <- vector("list", length(stn_list))

for (i in seq_along(stn_list)) {
  rain_stations_cf <- cf_station(stn_list[i]) 
  
  output[[i]] <- cf_query(user = me,
                          datatype = rain_dt,
                          station = rain_stations_cf,
                          # start_date = "1991-01-01 00",
                          start_date = "2017-01-01 00",
                          end_date = "2022-01-01 00") %>% 
    as.data.frame()
}

df <- output %>% bind_rows()
```

As you mention, CliFlo places a limit on the number of rows per subscription. This is certainly one of the disadvantages in calculating the annual rainfall using daily data.

**Comment by johnForne** [comment]
Amazing - thanks heaps Blake, much appreciated.

I've tried adding the argument `datatype = rain_dt` back in - but I'm getting some error that I don't understand (as below)...

```
> rain_dt <- cf_datatype(3, 1, 1)
> rain_stations = cf_find_station(
+   lat = -40.7,
+   long = 172.465,
+   rad = 840,
+   datatype = rain_dt, # Add the rain datatype to the query
+   search = "latlong",
+   status = "open"
+ )
Error:
! Assigned data `dmy(doc_table$Start, tz = "NZ")` must be compatible with existing data.
✖ Existing data has 624 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Unknown or uninitialised column: `Start`.
> 
```
I noticed this error when I tried using your code as above and noticed that it seemed to work when I hashed the datatype argument. From my non-expert read of the help for `cf_find_stations()` I assumed that because my was based on latlong because of the argument `search = "latlong`. And there my search was not based on datatypes and therefore I didn't need to use the datatype argument (which seemed to be causing the error to be thrown).

Do you know how to resolve the error I get when I add the `datatype = rain_dt`? Will the code still work if removing the `datatype = rain_dt` argument? What are the implications?

Anyhow, I tried hashing the `datatype = rain_dt` argument to check what happens... and unfortunately I get another error further down in the code (see below).

```
> rain_stations = cf_find_station(
+   lat = -40.7,
+   long = 172.465,
+   rad = 840,
+   # datatype = rain_dt, # Add the rain datatype to the query
+   search = "latlong",
+   status = "open"
+ )
> # Setup an empty list
> output <- vector("list", length(stn_list))
> for (i in seq_along(stn_list)) {
+   rain_stations_cf <- cf_station(stn_list[i])
+  
+   output[[i]] <- cf_query(user = me,
+                           datatype = rain_dt,
+                           station = rain_stations_cf,
+                           # start_date = "1991-01-01 00",
+                           start_date = "2017-01-01 00",
+                           end_date = "2022-01-01 00") %>%
+     as.data.frame()
+ }
connecting to CliFlo...
reading data...
Error: No rows? See this help link <http://cliflo.niwa.co.nz/pls/niwp/wh.do_help?id=nodata> for possible reasons
```
Any ideas why I still seem to be getting this error apparently relating to sites with no rows?

Thanks in advance,

John

**Comment by blasee** [comment]
Hi @johnForne, what version of `clifro` are you using?

```r
packageVersion("clifro")
```

You may like to try updating to the latest dev version to see if this fixes your issue:

```r
if (!require("devtools")) 
    install.packages("devtools")

devtools::install_github("ropensci/clifro")
```

Let me know how you go :-)
